### ISSUE TITLE
Multiple queued txs take a long time to sign and execute

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/safe-pm#27]
# Problem Owner

@usame-algan  

# Part 1: Define the problem

## What problem are you trying to solve?

Multiple queued txs take a long time to sign and execute for Safes requiring more than 1 signature.

## What is your hypothesis?

If we solve this problem, heavy users (teams, DAOs etc.) of the Safe (interface) will save time and money handling multiple txs at the same time.  

## What value does this bring to our customer and/or our mission? What is the goal?

Time and gas savings
Focusing on improving the experience for our most valuable user group
Improved user experience in times of longer backend latency 

## How do we measure it?

user requests 
no of events, where off-chain signatures for the same safe are added within a short time span (availability of data?)
alternatively no. of events where multiple txs are executed from the same safe within a given time span 

## Links:
  
Brainstorming board:
https://miro.com/app/board/uXjVOTUNud0=/
  

# Part 2: Shaping the problem 
  
### Allow execution of txs that are not next in line with their Safe Nonce 

**This solution is supposed to be implemented within this roadmap cycle.**

**Overview:** The interface is blocking users from executing transactions that are not next in line in terms of the SafeNonce. This was implemented to prevent users from executing transactions that will fail, if the SafeNonce of the executed tx is not in order. Heavy and experienced Safe users often are constrained by this restriction in times where the CGW has delayed responses about the state of the transaction.  The following solution does not lower the burden in terms of signing and executing multiple txs as they will remain individual steps, but it can greatly reduce the pain for heavy users in times of degraded CGW performance.

**Scope for v1:**

- [ ] add "Transaction execution order" section with checkbox ("allow tx execution out of order") to settings/advanced. provide information about the associated risks of losing funds for failed transactions (gas fees)
- [ ] enable "Execute" button for all transactions that reached signature threshold for users who have this feature enabled
- [ ] optional: show warning message in tx execution modal 
- [ ] explore estimation behavior and define viable option(s)

**Mocks:**

See Mock 1 below

**Risks:** 

Transactions will fail if the user does not execute transactions in order of the Safe Nonce. The transactions may fail if they are executed by different wallets, as the wallet's nonce protects the user from tx being mined not in the order of the Safe Nonce. This can result in loss of funds in the height of the transaction fee. Mitigation of this risk can be done by providing the user with the necessary information about this behavior and only allowing users to access this "feature" by specifically enabling it in the settings. 

Trade-off: This solution only addresses the part of the problem where users were unable to execute transactions as the backend did not index the successfully included previous transaction or where users simply want to execute all queued transactions as fast as possible. Estimation does not work with its current implementation and therefore the user would need to determine a safe Gas Limit. 

### Draft transactions 

**This solution is supposed to be explored within this roadmap cycle.** 

**Overview:** Allow the user to create transactions in draft mode with no possibility of signing or execution. These proposed drafts could then be bundled into a transaction batch, without the trade-offs that we have for non-draft batched transaction creation below. Draft transactions could also be turned into normal transactions without batching them. These draft transactions could be subject to comments, likes etc from Safe owners. 

**Scope:**

- [ ] further define the functionality of this feature
- [ ] create a design mock that can go through user testing
- [ ] align with infra on implementation of this tx type in the CGW 

**Mocks:**

see Mock 2 below

### Signing: 

Allowing the user to sign all queued txs that require their signature in a given Safe.
The user could select the transactions that he wants to sign. 

Risks: The user might not verify/check that he really wants to sign all of the included transactions. 

Trade-off: Each transaction needs an individual signature and therefore we cannot abstract all required signatures into one singular signing event. The user would still need to sign each transaction with their connected wallet. The value of "batch" signing is therefore strongly limited. 

Ivan: mobile wallet could allow batch signing

### Batching 

Allowing the user to create a batched transaction from multiple queued transactions. 

Risks and Trade-offs: 

- already provided signatures cannot be used for a newly created batched transaction and need to be provided again
- transactions that are included in the batched transaction and (A) have all required signatures or (B) only 1 missing signature are at risk of being executed again (after they have been executed in the batch) in the case of (A) by anyone and in case (B) by one of the owners of the Safe. these transactions would therefore need to be canceled to mitigate the risk. 
- transactions that are included in the batched transaction remain in the queue 
- deletion of transactions from the queue for such a usecase is not envisioned due to security risks

## Concept Mocks

Mock 1: Allow execution of txs that are not next in line with their Safe Nonce 

![batch execution feature drawio](https://user-images.githubusercontent.com/93598450/150985513-0fba9f50-8b8d-4a28-90c4-0baa57980e82.png)

Mock 2: Draft transactions

![Draft transactions drawio](https://user-images.githubusercontent.com/93598450/150994830-c79f3f4f-58cb-40f0-b79b-261fd8ada87e.png)
