### ISSUE TITLE
Low awareness of the mobile app among Web users

### ISSUE THREAD

**Issue by sche** [safe-global/safe-pm#54]
# Part 1: Define the problem

## To implement
- [x] Show the App banner on the dashboard
- [x] Show the App Store logo in the footer
~~Promote the App as an owner when adding owner keys in the Safe Creation flow~~ (Will be part of [High drop-off rate](https://github.com/safe-global/safe-pm/issues/82) problem statement)

## What problem are you trying to solve?

For many existing Web users, Mobile App is not visible. Many users discover the app by chance or overhear it from others.
We added Connect with the Mobile feature but can do more than that. Some of the initial ideas of what we can do:
* Offer to use mobile keys when creating a new Safe
* Offer to import Safe on mobile by a QR code once it was created
* Promote mobile to receive push notifications once other owners sign transaction
* Promote new mobile features in What's New on Web
* Promote Ledger Nano X on mobile

## What is your hypothesis?

* If we research further the Customer Journey Map (especially the Discovery phase), we will understand our audience better.
* If we improve the connection (relation) of the mobile app in the Web/Browser versions, we can attract a new audience.

## What value does this bring to our customer and/or our mission? What is the goal?

* Improve our users' whole experience by allowing them to be up-to-date, access their portfolios, and take actions when they can't access their PC. 

## How do we measure it?

* The total amount of active users on Mobile
* The ratio between Web and Mobile users

## Links:
  
TBD
  
  

# Part 2: Shaping the problem 
  To improve awareness of the mobile app among Web Users the mobile app should be promoted more on the web app, in social media, landing page

## Problem Owner

@liliya-soroka 
@DmitryBespalov 

## Solution
There is no real way to improve awareness among the web users from the mobile team side only. There are a few solutions that may influence in a good direction on the mobile app but help from the web team, safe-apps team, marketing are required. All of them are low efforts required

### Solution 1  
- [ ] Add prominent information about the mobile app inside the web app with the possibility to download the mobile app following the link in the web app  - https://github.com/gnosis/safe-react/pull/3710
The button is available in the footer only on the Welcome page and in the settings. We would like to keep it for a few web releases to track clicks and analyse if it may have a good impact on the web users
Within the next 2-4 weeks there is the capacity to work together Marketing team and designer team to prepare the next drafts:
- Jorge to share Twitter Thread + accompanying blog post and the visual design 
- Influencer mobile app story 
- Educational series, with some visual aid
- Cover pages for Twitter, Medium, etc.

### Solution 2
- [ ]  Show the mobile app among the list of available wallets.
It will build an association in the users' minds between the mobile app and wallet that may be used for interaction with the web UI.
To implement the solution the migration to onboard.js v2 is required. The task is in progress as the eco-system Friday project - https://github.com/gnosis/safe-react/pull/3626
![Group 484](https://user-images.githubusercontent.com/93707525/160362979-930ec473-732d-4669-850d-f2996440f119.png)
<img width="818" alt="image" src="https://user-images.githubusercontent.com/338622/160376880-4c1a9e7a-fa49-4e8d-9a1a-a681b86a9774.png">

### Solution 3
- [ ] Promote mobile app ( dApps option on mobile) when WallectConnect safe app is used on the web, and there are no safe apps for this dApp on the web. 
"dApps" section in the mobile app is the easiest, available any time from any place way to interact with your favourite dApps from your mobile device.
The promotion text will be added on the web when the WC safe app is used, and there are no appropriate safe apps for the connected app.

### Solution 4
- [ ] Prepare content strategy together with the marketing team to promote the mobile app in the community via social networks, blog posts, website.
![Frame 491](https://user-images.githubusercontent.com/93707525/160363464-c10e7b29-c3f9-429d-81e9-c12b7d694a3d.png)

**Overview**
  
**Rough Scoping & Timeline**

**Risk(s), Key Trade Offs & Decisions**

**Concept Mocks**
  
## Alternative solutions & ideas

1. Add a widget with the mobile app promotion on the web dashboard when it's ready
![Screenshot 2022-03-25 at 17 14 1](https://user-images.githubusercontent.com/93707525/160364267-81f6dff5-d624-4db1-ab4a-20131fe217a2.png)

 3. Promote "owner account generation on mobile" for a new safe during safe creation flow and during Owner management in the settings. It may be a step in the "EOA" wallet direction for the mobile app. 
 A user will generate a key ( account) on the mobile app and use it as an owner during safe creation or owners management in the safe.
The solution will require efforts from the designer team, safe web team and mobile team to define the flow before actual implementation 

4. Make the mobile app existent more prominent on the landing page.
The landing pages of the multi-platform projects usually have prominent mention of all supported platforms either via images or via banners with the "apps store" and "google play" buttons without the need to scroll a page down. 
On https://gnosis-safe.io/ open app ( link on the web app) is a quick, easy to access and good visualized possibility to open the app in a few clicks.
To get more information about the mobile app a user has to scroll down

## Open Questions

- Why are our users start downloading the mobile app? 
- Those who don't hear about it from others, but discover it independently: how do they find it? Through the App Stores, by googling one or from the website?
